# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkXdlecEquU-NshzSa7knmRaVyh742-g
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

d=sns.load_dataset("titanic")
d

d.isnull().sum()

cr=["alive","alone"]
k=d.drop(columns=cr)

k['age'].fillna(round(k['age'].mean()))
k['embark_town'].fillna(k['embark_town'].mode()[0])

nc=k.select_dtypes(include=[np.number]).columns.tolist()

plt.figure(figsize=(12,8))
k.hist(figsize=(12,8))
plt.show()

plt.figure(figsize=(12,8))
sns.boxplot(data=k)
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12,8))
sns.scatterplot(x=k['age'],y=k['fare'])
plt.show()

sns.pairplot(k,diag_kind='kde')
plt.show()

corr=k[['age','fare']].corr('pearson')
cv=k[['age','fare']].cov()
print(corr,"\n",cv)

plt.figure(figsize=(12,8))
cm=k[nc].corr('pearson')
sns.heatmap(cm,cmap='coolwarm')
plt.show()

