# -*- coding: utf-8 -*-
"""prog5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11x7CJcNPMdKjpmjS7Zh4RgQU6yR2ebFh
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score

iris = sns.load_dataset("iris")

iris.head()

iris.shape

iris.info()

iris.describe()

plt.figure(figsize=(12,8))
iris.hist(figsize=(12,8))
plt.suptitle("Hist")
plt.show()

plt.figure(figsize=(12,8))
sns.boxplot(data=iris)
plt.xticks(rotation=45)
plt.suptitle("Hist")
plt.show()

nc=iris.select_dtypes(include=[np.number]).columns
cc=iris.select_dtypes(include=['object']).columns
print(nc,"\n",cc)

plt.figure(figsize=(10,6))
corrm=iris[nc].corr('pearson')
sns.heatmap(corrm,cmap='coolwarm')
plt.suptitle("Hist")
plt.show()

# labelen=LabelEncoder()
# iris["species"]=labelen.fit_transform(iris["species"])

X=iris.drop(columns=["species"])
y=iris["species"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

def eval(k_values,weights="uniform"):
  results={}
  for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k,weights=weights)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    ac=accuracy_score(y_test,y_pred)
    f1=f1_score(y_test,y_pred,average='weighted')
    results[k]={'accuracy':ac,'f1score':f1}
  return results

k_values=[1,2,3]
rv=eval(k_values,weights='uniform')
uv=eval(k_values,weights='distance')

rdf=pd.DataFrame.from_dict({
    'rb':rv,
    'bb':uv
})
rdf

