# -*- coding: utf-8 -*-
"""prog3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMZ8QoUShV3xV5ktV1pXA7FyZkerKEbk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

iris=datasets.load_iris()

X=iris.data
y=iris.target
sca=StandardScaler()
X_scaled=sca.fit_transform(X)
pca=PCA()
X_pca=pca.fit_transform(X_scaled)
colors=['red','green','blue']

cm=np.cov(X_scaled.T)
ec, evc =np.linalg.eig(cm)
print(cm,"\nEV:",ec,"\nEVC:",evc)

fig=plt.figure(figsize=(12,8))
ax=fig.add_subplot(111,projection='3d')
for i in range(len(colors)):
  ax.scatter(X_scaled[y==i,0],X_scaled[y==i,1],X_scaled[y==i,2],color=colors[i])

plt.figure(figsize=(12,8))
for i in range(len(colors)):
  plt.scatter(X_pca[y==i,0],X_pca[y==i,1],color=colors[i])

plt.legend()
plt.grid()
plt.show()

fig = plt.figure(figsize=(12,8))
ax=fig.add_subplot(111,projection='3d')
for i in range(len(colors)):
  ax.scatter(X_scaled[y==i,1],X_scaled[y==i,0],X_scaled[y==i,2],color=colors[i])
for i in range(3):
  ax.quiver(0,0,0,evc[i,0],evc[i,1],evc[i,2])

plt.show()

